eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
#    service-url:
#      service-url:
#        defaultZone: http://localhost:8080/
#  server:
#    enable-self-preservation: false
server:
  port: 8090
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka